import type { Metadata } from 'next'
import { Geist, Geist_Mono } from 'next/font/google'
import './globals.css'
import Header from '@/widgets/header/header'
import Footer from '@/widgets/footer/footer'
import QueryProviders from '@/providers/query-provider'
import {
  dehydrate,
  HydrationBoundary,
  QueryClient,
} from '@tanstack/react-query'
import { getCounters } from '@/features/counters/actions/actions'

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
})

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
})

export const metadata: Metadata = {
  title: 'Qpick',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  const queryClient = new QueryClient()

  const initialCounters = await getCounters()
  return (
    <html lang="en">
      <QueryProviders>
        <body className={`${geistSans.variable} ${geistMono.variable}`}>
          <HydrationBoundary state={dehydrate(queryClient)}>
            <div className="container">
              <div className="layout">
                <Header initialCounters={initialCounters} />
                <main className="main">{children}</main>
                <Footer />
              </div>
            </div>
          </HydrationBoundary>
        </body>
      </QueryProviders>
    </html>
  )
}
