import type { Metadata } from 'next'
import { Geist, Geist_Mono } from 'next/font/google'
import './globals.css'
import QueryProviders from '@/providers/query-provider'
import {
  dehydrate,
  HydrationBoundary,
  QueryClient,
} from '@tanstack/react-query'
import Header from '@/widgets/header/header'
import Footer from '@/widgets/footer/footer'
import { getCounters } from '@/features/counters/actions/actions'
import { getCurrentSession } from '@/features/auth/actions/actions'
import { createTheme, ThemeProvider } from '@mui/material'
import CssBaseline from '@mui/material/CssBaseline'
import { revalidatePath } from 'next/cache'

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
})

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
})

export const metadata: Metadata = {
  title: 'Qpick',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  const queryClient = new QueryClient()

  const initialCounters = await getCounters()
  const session = await getCurrentSession()

  return (
    <QueryProviders>
      <HydrationBoundary state={dehydrate(queryClient)}>
        <html lang="en">
          <body className={`${geistSans.variable} ${geistMono.variable}`}>
            <div className="container">
              <div className="layout">
                <Header
                  initCartCount={initialCounters.cartItemsCount}
                  isLogged={!!session?.user.id}
                />
                <div className="main">{children}</div>
                <Footer />
              </div>
            </div>
          </body>
        </html>
      </HydrationBoundary>
    </QueryProviders>
  )
}
